### ISSUE TITLE
Getting a record using the index?

### ISSUE THREAD

**Issue by fulviocanducci** [wtulloch/Blazor.IndexedDB#7]
Help please: getting a record using the index?

missing example please

I tried a code and it didn't work

example:

```csharp
public async Task<IList<T>> AllDoneAsync(bool done)
{            
            return await DbManager.GetAllRecordsByIndex<bool, T>(new StoreIndexQuery<bool>()
            {
                Storename = Storename(),
                AllMatching = true,
                IndexName = "done",
                QueryValue = done            
            });
}
```

**Comment by fulviocanducci** [comment]
If you can exemplify this method `DbManager.GetAllRecordsByIndex` ?

**Comment by wtulloch** [comment]
Your code is correct the issue is with IndexedDB itself. To put simply IndexedDB does not index on Boolean values. So even though you can create the index it won't be used.

There are a few of ways you can get around this. 

1. change your done property to either an int or string (I have tested this)
2. Provide an additional property that returns Done as a string or int and set the index on that
3. Return all of the items and then filter on  the Done property.

Hope that helps

**Comment by fulviocanducci** [comment]
@wtulloch thanks ...
